a=(1,2,3,4,5,6,7,8,9,10)
b=(1,2,3,4)                                                                                                                                                                                                                                                                                                                                                                    
print(a in b)
print(b in a)
print(b not in a)